### ISSUE TITLE
setCountries, unused _permitted argument

### ISSUE THREAD

**Issue by Wozacosta** [zerolawtech/SFT-Protocol#58]
Hi there !

There's a discrepancy between the documentation and the implementatoin of IssuingEntity.setCountries

https://sft-protocol.readthedocs.io/en/latest/issuing-entity.html#IssuingEntity.setCountries
https://github.com/zerolawtech/SFT-Protocol/blob/master/contracts/IssuingEntity.sol#L344

The boolean parameter `_permitted` is not taken into account by IssuingEntity.setCountries()

**Comment by nymd** [comment]
Thanks for noting this!  After discussing with Ben, we determined this was a documentation issue. The permitted bool is meant only to be used with setCountry.  The fix will be merged in to the docs shortly.
