### ISSUE TITLE
KeyError: Compiler

### ISSUE THREAD

**Issue by camillion154** [zerolawtech/SFT-Protocol#61]
Hello, 

I followed your readthedocs but I keep getting an error when attempting to load SFT-protocol. 

In the terminal, I navigate to the "SFT-protocol-master" directory. 

I run the command: 
> brownie console

and I get this error log: 

File "brownie/cli/__main__.py", line 53, in main
    importlib.import_module(f"brownie.cli.{args['<command>']}").main()
  File "brownie/cli/console.py", line 26, in main
    active_project = project.load()
  File "brownie/project/main.py", line 330, in load
    return Project(project_path, name)
  File "brownie/project/main.py", line 99, in __init__
    self.load()
  File "brownie/project/main.py", line 107, in load
    self._compiler_config = load_project_compiler_config(self._project_path, "solc")
  File "brownie/_config.py", line 87, in load_project_compiler_config
    return config_data['compiler'][compiler]
KeyError: 'compiler'

I'm on Mac OS Mojave 10.14.6, but I also tried setting up on windows and got the same error. 

Thanks for your help

**Comment by iamdefinitelyahuman** [comment]
Ahh sorry about that. `brownie-config.json` wasn't updated after the latest release of Brownie released, and there were breaking changes to it's format.  Should be fixed with https://github.com/zerolawtech/SFT-Protocol/commit/f2c671700375b7f10187601c9bca333b5ba30107

**Comment by iamdefinitelyahuman** [comment]
As a side note, Brownie is about to go out of beta so this (hopefully) shouldn't happen again :)

**Comment by camillion154** [comment]
Thank you!
